using System;

namespace vbamc.Vba
{
    public class VbaProjectStream
    {
        /// <summary>
        /// Version generated by Office 2003.
        /// </summary>
        public const short VersionOffice2003 = 0x0079;

        /// <summary>
        /// Version generated by Office 365.
        /// </summary>
        public const short VersionOffice365 = 0x00B2;

        /// <summary>
        /// Implementations other the Office applications must use the version
        /// number 0xFFFF so that performance caches are ignored.
        /// </summary>
        public const ushort Version = 0xFFFF;

        // Reserved constants
        public const short Reserved1 = 0x61CC;
        public const byte Reserved2 = 0x00;
        public const byte Reserved3 = 0x0001;

        public byte[] Generate()
        {
            var memory = new MemoryStream();
            var writer = new BinaryWriter(memory);

            // _VBA_PROJECT stream header
            writer.Write(Reserved1);
            // (1.6) To be interoperable, this version number MUST be set to 0xFFFF so that performance caches are ignored.
            writer.Write(Version);
            writer.Write(Reserved2);
            writer.Write(Reserved3);

            // omit the PerformanceCache record (see 1.6 Versioning and Localization)
            
            writer.Close();
            return memory.ToArray();
        }
    }
}
